function [metrics, controller_names, metrics_table] = extract_multiagent_control_metrics(global_results, Ts_Sim)

controller_names = fieldnames(global_results);
nC = numel(controller_names);

metrics.collective_control_cost = zeros(1, nC);
metrics.collective_pos_rmse     = zeros(1, nC);
metrics.collective_form_rmse    = zeros(1, nC);
metrics.leader_pos_rmse         = zeros(1, nC);
metrics.worst_agent_pos_rmse    = zeros(1, nC);
metrics.simtime                 = zeros(1, nC);

for k = 1:nC
    name = controller_names{k};
    res = global_results.(name);

    U = res.U;           % 4 x N x Nd
    X = res.X;           % 12 x N x Nd
    X_ref = res.X_ref;   % 12 x N x Nd
    F = res.formation_error;   % 3 x N x Nd

    Nd = size(X,3);

    % collective control cost
    cost_sum = 0;
    for d = 1:Nd
        Ud = U(:,:,d);
        cost_sum = cost_sum + Ts_Sim * sum(sum(Ud.^2, 1));
    end
    metrics.collective_control_cost(k) = cost_sum;

    % per-agent position RMSE
    pos_rmse_agents = zeros(1,Nd);
    for d = 1:Nd
        pos_error = X(1:3,:,d) - X_ref(1:3,:,d);
        pos_rmse_agents(d) = sqrt(mean(sum(pos_error.^2, 1)));
    end

    metrics.collective_pos_rmse(k) = sqrt(mean(pos_rmse_agents.^2));
    metrics.leader_pos_rmse(k) = pos_rmse_agents(1);
    metrics.worst_agent_pos_rmse(k) = max(pos_rmse_agents);

    % formation RMSE, followers only
    form_rmse_agents = zeros(1,Nd-1);
    for d = 2:Nd
        ferr = F(:,:,d);
        form_rmse_agents(d-1) = sqrt(mean(sum(ferr.^2, 1)));
    end
    metrics.collective_form_rmse(k) = sqrt(mean(form_rmse_agents.^2));

    % sim time
    metrics.simtime(k) = res.simtime;
end

metrics_table = table( ...
    controller_names, ...
    metrics.collective_control_cost.', ...
    metrics.collective_pos_rmse.', ...
    metrics.collective_form_rmse.', ...
    metrics.simtime.', ...
    'VariableNames', { ...
        'Controller', ...
        '\makecell{Collective\\Control Cost}', ...
        '\makecell{Collective RMS\\Tracking Error (m)}', ...
        '\makecell{Collective RMS\\Formation Error (m)}', ...
        'SimTime' ...
    } ...
);

end

% metrics_table = table( ...
%     controller_names, ...
%     metrics.collective_control_cost.', ...
%     metrics.collective_pos_rmse.', ...
%     metrics.collective_form_rmse.', ...
%     metrics.leader_pos_rmse.', ...
%     metrics.worst_agent_pos_rmse.', ...
%     metrics.simtime.', ...
%     'VariableNames', { ...
%         'Controller', ...
%         '\makecell{Collective\\Control Cost}', ...
%         '\makecell{Collective RMS\\Tracking Error (m)}', ...
%         '\makecell{Collective RMS\\Formation Error (m)}', ...
%         '\makecell{Leader RMS\\Tracking Error (m)}', ...
%         '\makecell{Worst-Agent RMS\\Tracking Error (m)}', ...
%         'SimTime' ...
%     } ...
% );