function [mc_metrics, controller_names, metrics_table] = extract_monte_carlo_metrics(mc_results, Ts_Sim)
    controller_names = fieldnames(mc_results);
    nC = numel(controller_names);
    nRuns = numel(mc_results.(controller_names{1}).run);

    % Preallocate raw data
    mc_metrics.raw.control_cost        = nan(nRuns, nC);
    mc_metrics.raw.control_mags        = nan(nRuns, 4, nC);
    mc_metrics.raw.control_smoothness  = nan(nRuns, nC);
    mc_metrics.raw.pos_rmse             = nan(nRuns, nC);
    mc_metrics.raw.att_rmse              = nan(nRuns, nC);
    mc_metrics.raw.simtime             = nan(nRuns, nC);

    % -------- Extract single-run metrics for every controller/run --------
    for k = 1:nC
        name = controller_names{k};

        for r = 1:nRuns
            tmp_results.(name) = mc_results.(name).run(r);
            metrics = extract_control_metrics(tmp_results, Ts_Sim);

            mc_metrics.raw.control_cost(r,k)        = metrics.control_cost;
            mc_metrics.raw.control_mags(r,:,k)      = metrics.control_mags(:,1).';
            mc_metrics.raw.control_smoothness(r,k)  = metrics.control_smoothness;
            mc_metrics.raw.pos_rmse(r,k) = metrics.pos_rmse;
            mc_metrics.raw.att_rmse(r,k)      = metrics.att_rmse;
            mc_metrics.raw.simtime(r,k)             = metrics.simtime;

            tmp_results = struct(); % reset
        end
    end

    % -------- Mean / Std / SEM / 95% CI --------
    fields = {'control_cost', 'control_smoothness', 'pos_rmse', ...
              'att_rmse', 'simtime'};

    for i = 1:numel(fields)
        f = fields{i};
        X = mc_metrics.raw.(f);

        mc_metrics.mean.(f) = mean(X, 1);
        mc_metrics.std.(f)  = std(X, 0, 1);
        mc_metrics.sem.(f)  = mc_metrics.std.(f) ./ sqrt(nRuns);
        mc_metrics.ci95.(f) = 1.96 * mc_metrics.sem.(f);
    end

    % Control magnitudes handled separately
    mc_metrics.mean.control_mags = squeeze(mean(mc_metrics.raw.control_mags, 1)); % 4 x nC
    mc_metrics.std.control_mags  = squeeze(std(mc_metrics.raw.control_mags, 0, 1));
    mc_metrics.sem.control_mags  = mc_metrics.std.control_mags ./ sqrt(nRuns);
    mc_metrics.ci95.control_mags = 1.96 * mc_metrics.sem.control_mags;

    % -------- Build metrics table --------
    metrics_table = table( ...
        controller_names, ...
        mc_metrics.mean.control_cost.', ...
        mc_metrics.std.control_cost.', ...
        mc_metrics.mean.pos_rmse.', ...
        mc_metrics.std.pos_rmse.', ...
        mc_metrics.mean.simtime.', ...
        'VariableNames', { ...
            'Controller', ...
            '\makecell{Mean Control\\ Cost}', ...
            '\makecell{Std Control\\ Cost}', ...
            '\makecell{Mean RMS \\Tracking Error}', ...
            '\makecell{Std RMS \\Tracking Error}', ...
            '\makecell{Mean\\ SimTime}'
        } ...
    );
end

% %% function that gives everything
%     % -------- Build metrics table --------
%     metrics_table = table( ...
%         controller_names, ...
%         mc_metrics.mean.control_cost.', ...
%         mc_metrics.std.control_cost.', ...
%         mc_metrics.mean.control_smoothness.', ...
%         mc_metrics.std.control_smoothness.', ...
%         mc_metrics.mean.pos_rmse.', ...
%         mc_metrics.std.pos_rmse.', ...
%         mc_metrics.mean.att_rmse.', ...
%         mc_metrics.std.att_rmse.', ...
%         mc_metrics.mean.simtime.', ...
%         'VariableNames', { ...
%             'Controller', ...
%             '\makecell{Mean Control\\ Cost}', ...
%             '\makecell{Std Control\\ Cost}', ...
%             '\makecell{Mean Control\\ Smoothness}', ...
%             '\makecell{Std Control\\ Smoothness}', ...
%             '\makecell{Mean RMS \\Tracking Error}', ...
%             '\makecell{Std RMS \\Tracking Error}', ...
%             '\makecell{Mean RMS \\Attitude Error}', ...
%             '\makecell{Std RMS \\Attitude Error}', ...
%             '\makecell{Mean\\ SimTime}'
%         } ...
%     );
% function [mc_metrics, controller_names, metrics_table] = extract_monte_carlo_metrics(mc_results, Ts_Sim)
% %EXTRACT_MONTE_CARLO_METRICS Extract Monte Carlo statistics from controller results.
% %
% % Inputs:
% %   mc_results : struct with fields per controller:
% %                mc_results.<controller>.run(k)
% %   Ts_Sim     : simulation sample time
% %
% % Outputs:
% %   mc_metrics : struct containing raw samples and summary statistics
% %   controller_names : n x 1 cell array
% %   metrics_table : MATLAB table combining Monte Carlo metrics
% 
%     controller_names = fieldnames(mc_results);
%     nC = numel(controller_names);
%     nRuns = numel(mc_results.(controller_names{1}).run);
% 
%     % Preallocate raw data
%     mc_metrics.raw.control_cost        = nan(nRuns, nC);
%     mc_metrics.raw.control_mags        = nan(nRuns, 4, nC);
%     mc_metrics.raw.control_smoothness  = nan(nRuns, nC);
%     mc_metrics.raw.rmse = nan(nRuns, nC);
%     mc_metrics.raw.att_rmse      = nan(nRuns, nC);
%     mc_metrics.raw.simtime             = nan(nRuns, nC);
% 
%     % -------- Extract single-run metrics for every controller/run --------
%     for k = 1:nC
%         name = controller_names{k};
% 
%         for r = 1:nRuns
%             tmp_results.(name) = mc_results.(name).run(r);
%             metrics = extract_control_metrics(tmp_results, Ts_Sim);
% 
%             mc_metrics.raw.control_cost(r,k)        = metrics.control_cost;
%             mc_metrics.raw.control_mags(r,:,k)      = metrics.control_mags(:,1).';
%             mc_metrics.raw.control_smoothness(r,k)  = metrics.control_smoothness;
%             mc_metrics.raw.rmse(r,k) = metrics.rmse;
%             mc_metrics.raw.att_rmse(r,k)      = metrics.att_rmse;
%             mc_metrics.raw.simtime(r,k)             = metrics.simtime;
% 
%             tmp_results = struct(); % reset
%         end
%     end
% 
%     % -------- Mean / Std / SEM / 95% CI --------
%     fields = {'control_cost', 'control_smoothness', 'rmse', ...
%               'att_rmse', 'simtime'};
% 
%     for i = 1:numel(fields)
%         f = fields{i};
%         X = mc_metrics.raw.(f);
% 
%         mc_metrics.mean.(f) = mean(X, 1);
%         mc_metrics.std.(f)  = std(X, 0, 1);
%         mc_metrics.sem.(f)  = mc_metrics.std.(f) ./ sqrt(nRuns);
%         mc_metrics.ci95.(f) = 1.96 * mc_metrics.sem.(f);
%     end
% 
%     % Control magnitudes handled separately
%     mc_metrics.mean.control_mags = squeeze(mean(mc_metrics.raw.control_mags, 1)); % 4 x nC
%     mc_metrics.std.control_mags  = squeeze(std(mc_metrics.raw.control_mags, 0, 1));
%     mc_metrics.sem.control_mags  = mc_metrics.std.control_mags ./ sqrt(nRuns);
%     mc_metrics.ci95.control_mags = 1.96 * mc_metrics.sem.control_mags;
% 
%     % -------- Build metrics table --------
%     metrics_table = table( ...
%         controller_names, ...
%         mc_metrics.mean.rmse.', ...
%         mc_metrics.std.rmse.', ...
%         mc_metrics.ci95.rmse.', ...
%         mc_metrics.mean.att_rmse.', ...
%         mc_metrics.std.att_rmse.', ...
%         mc_metrics.ci95.att_rmse.', ...
%         mc_metrics.mean.control_cost.', ...
%         mc_metrics.std.control_cost.', ...
%         mc_metrics.ci95.control_cost.', ...
%         mc_metrics.mean.control_smoothness.', ...
%         mc_metrics.std.control_smoothness.', ...
%         mc_metrics.ci95.control_smoothness.', ...
%         mc_metrics.mean.simtime.', ...
%         mc_metrics.std.simtime.', ...
%         mc_metrics.ci95.simtime.', ...
%         'VariableNames', { ...
%             'Controller', ...
%             '\makecell{Mean Tracking\\ Error Norm}', ...
%             '\makecell{Std Tracking\\ Error Norm}', ...
%             '\makecell{95\% CI Tracking\\ Error Norm}', ...
%             '\makecell{Mean Attitude\\ Error Norm}', ...
%             '\makecell{Std Attitude\\ Error Norm}', ...
%             '\makecell{95\% CI Attitude\\ Error Norm}', ...
%             '\makecell{Mean Control\\ Cost}', ...
%             '\makecell{Std Control\\ Cost}', ...
%             '\makecell{95\% CI Control\\ Cost}', ...
%             '\makecell{Mean Control\\ Smoothness}', ...
%             '\makecell{Std Control\\ Smoothness}', ...
%             '\makecell{95\% CI Control\\ Smoothness}', ...
%             '\makecell{Mean\\ SimTime}', ...
%             '\makecell{Std\\ SimTime}', ...
%             '\makecell{95\% CI\\ SimTime}' ...
%         } ...
%     );
% end