#ifndef PORTABLE_WORDSIZES
#ifdef __MW_TARGET_USE_HARDWARE_RESOURCES_H__
#ifndef __MW_TARGET_HARDWARE_RESOURCES_H__
#define __MW_TARGET_HARDWARE_RESOURCES_H__

#define MW_MULTI_TASKING_MODE 1
#include "MW_PX4_TaskControl.h"

#define MW_USECODERTARGET 1
#define MW_TARGETHARDWARE PX4 Host Target
#define MW_CONNECTIONINFO_XCPONTCPIP_IPADDRESS codertarget.pixhawk.registry.getLoopbackIP
#define MW_CONNECTIONINFO_XCPONTCPIP_PORT 17725
#define MW_CONNECTIONINFO_XCPONTCPIP_VERBOSE 1
#define MW_EXTMODE_CONFIGURATION XCP on TCP/IP
#define MW_EXTMODE_RUNNING on
#define MW_RTOS NuttX
#define MW_RTOSBASERATETASKPRIORITY 250
#define MW_SCHEDULER_INTERRUPT_SOURCE 0
#define MW_RUNTIME_BUILDACTION 1
#define MW_CMAKECONFIG 0
#define MW_SIMULATOR 0
#define MW_SIMULINKIO_MODELTRANSPORTDATAFCN px4.internal.ConnectedIO.getConfigsetInfo
#define MW_SIMULINKIO_SERVERDEPLOYFCN px4.internal.ConnectedIO.buildAndDeployPX4IOServer
#define MW_HRT_CONSTRAINT 0
#define MW_SEM_WATERMARK 20
#define MW_OBC_CONNECTIVITY_IP 127.0.0.1
#define MW_IOBLOCKSMODE deployed
#define MW_DATAVERSION 2016.02

#endif /* __MW_TARGET_HARDWARE_RESOURCES_H__ */

#endif

#endif
